/**
 * 统一业务错误类
 * code: 机器可读错误码（前端用于 i18n 翻译）
 * statusCode: HTTP 状态码（默认 400）
 * detail: 可选的上下文信息（如字段名、限制值）
 */
export class AppError extends Error {
  constructor(code, statusCode = 400, detail = null) {
    super(code)
    this.code = code
    this.statusCode = statusCode
    this.detail = detail
  }
}

// ─── 错误码常量 ───
export const E = {
  // 认证
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',
  CODE_INVALID: 'CODE_INVALID',
  CODE_EXPIRED: 'CODE_EXPIRED',
  CODE_TOO_MANY_ATTEMPTS: 'CODE_TOO_MANY_ATTEMPTS',
  QQ_NOT_REGISTERED: 'QQ_NOT_REGISTERED',

  // 画师
  ARTIST_NOT_FOUND: 'ARTIST_NOT_FOUND',
  NAME_EMPTY: 'NAME_EMPTY',
  CODE_FORMAT: 'CODE_FORMAT',
  CODE_TAKEN: 'CODE_TAKEN',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_URL: 'INVALID_URL',

  // 流程
  STAGE_NOT_FOUND: 'STAGE_NOT_FOUND',
  STAGE_NAME_EMPTY: 'STAGE_NAME_EMPTY',
  FINAL_CANNOT_DISABLE: 'FINAL_CANNOT_DISABLE',
  FINAL_CANNOT_DELETE: 'FINAL_CANNOT_DELETE',
  FINAL_READONLY: 'FINAL_READONLY',
  MAX_INSTALLMENTS: 'MAX_INSTALLMENTS',
  FINAL_TOO_LOW: 'FINAL_TOO_LOW',
  MIN_STAGES: 'MIN_STAGES',
  REORDER_LENGTH: 'REORDER_LENGTH',
  REORDER_INVALID: 'REORDER_INVALID',
  REORDER_DUPLICATE: 'REORDER_DUPLICATE',
  NO_FINAL: 'NO_FINAL',
  NOT_PAYMENT_STAGE: 'NOT_PAYMENT_STAGE',
  BP_TOO_LOW: 'BP_TOO_LOW',
  BP_TOO_HIGH: 'BP_TOO_HIGH',
  NO_PAYMENT_NODE: 'NO_PAYMENT_NODE',
  SUM_NOT_100: 'SUM_NOT_100',

  // 订单
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  DELIVER_WRONG_STATUS: 'DELIVER_WRONG_STATUS',
  TIER_NOT_FOUND: 'TIER_NOT_FOUND',
  ILLEGAL_PATH: 'ILLEGAL_PATH',
  MISSING_FILE: 'MISSING_FILE',

  // 通用
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION: 'VALIDATION',

  // 画师扩展
  SUBDOMAIN_FORMAT: 'SUBDOMAIN_FORMAT',

  // 订单扩展
  ORDER_INVALID_STATUS: 'ORDER_INVALID_STATUS',
  QUEUE_EMPTY: 'QUEUE_EMPTY',
  QUEUE_NOT_OWNED: 'QUEUE_NOT_OWNED',
  QUEUE_LENGTH: 'QUEUE_LENGTH',
  QUEUE_DUPLICATE: 'QUEUE_DUPLICATE',
  INVALID_PRIORITY: 'INVALID_PRIORITY',

  // 上传
  ILLEGAL_FILE_TYPE: 'ILLEGAL_FILE_TYPE',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',

  // 管理员
  ADMIN_VERIFY_FAILED: 'ADMIN_VERIFY_FAILED'
}
