# backup-log.ps1 - UTF-8 timestamped log writer for daily-backup.bat (P2-E)
#
# Usage:
#   powershell -NoProfile -ExecutionPolicy Bypass -File scripts\backup-log.ps1 -LogPath <logfile> -Message <text>
#
# Discipline (P2-E):
#   - Timestamps are generated by PowerShell and written as UTF-8, avoiding cmd %date%/%time%
#     mojibake under a GBK codepage.
#   - Message text must be ASCII (called from an ASCII-only batch file).
param(
  [Parameter(Mandatory = $true)][string]$LogPath,
  [Parameter(Mandatory = $true)][string]$Message
)
$ErrorActionPreference = 'Stop'

$line = '[' + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') + '] ' + $Message
Add-Content -LiteralPath $LogPath -Value $line -Encoding utf8
